export const Fonts = Object.freeze({
  Black: 'Poppins-Black',
  BlackItalic: undefined,
  Bold: 'Poppins-Bold',
  BoldItalic: 'Poppins-BoldItalic',
  ExtraBold: undefined,
  ExtraBoldItalic: undefined,
  Italic: 'Poppins-Italic',
  Light: 'Poppins-Light',
  LightItalic: undefined,
  Medium: 'Poppins-Medium',
  MediumItalic: undefined,
  Regular: 'Poppins-Regular',
  SemiBold: 'Poppins-SemiBold',
  SemiBoldItalic: undefined,
});
